exclude: [gulpfile.js, package.json, node_modules, Gemfile, Gemfile.lock]
baseurl: ""
future: true
permalink: /life/:year-:month-:day_:slug/
excerpt_separator: <!--more-->
paginate: 5
paginate_path: "/life/page:num/"
root_breadcrumb: "/:ЦССВ «Сколковский»"
plugins: [jekyll-paginate]

collections:
  albums:
    output: true
    permalink: /gallery/:path/
  montessori:
    output: true
    permalink: /projects/montessori/:path/
  elderyhelp:
    output: true
    permalink: /projects/eldery-help/:path/
  children:
    output: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "projects"
      type: pages
    values:
      section_breadcrumb: "/projects/:Проекты"
  -
    scope:
      path: "information"
      type: pages
    values:
      section_breadcrumb: "/information/:Сведения об образовательной организации"
  -
    scope:
      path: ""
      type: posts
    values:
      layout: "post"
      cover_image_key: 0
      files_subdir: life
      section_breadcrumb: "/life/:Новости"
  -
    scope:
      path: ""
      type: montessori
    values:
      layout: "post"
      cover_image_key: 0
      files_subdir: montessori
      section_breadcrumb: "/projects/:Проекты|/projects/montessori/:Монтессори-технологии в Центре"
  -
    scope:
      path: ""
      type: elderyhelp
    values:
      layout: "post"
      cover_image_key: 0
      files_subdir: eldery-help
      section_breadcrumb: "/projects/:Проекты|/projects/eldery-help/:Помощь пожилым людям"
  -
    scope:
      path: ""
      type: albums
    values:
      layout: "album"
      cover_image_key: 0
      section_breadcrumb: "/gallery/:Галерея"
  -
    scope:
      path: ""
      type: children
    values:
      single_image: true
      files_subdir: children
      no_more_link: true
