exclude: [gulpfile.js, package.json, node_modules, Gemfile, Gemfile.lock]
baseurl: ""
future: true
permalink: /life/:year-:month-:day-:slug/
excerpt_separator: <!--more-->
paginate: 5
paginate_path: "/life/page:num/"
root_breadcrumb: "/~ЦССВ «Сколковский»"
plugins: [jekyll-paginate]

collections:
  albums:
    output: true
    permalink: /gallery/:path/
  announces:
    output: true
    permalink: /announces/:path/
  media:
    output: true
    permalink: /media/:path/
  montessori:
    output: true
    permalink: /projects/montessori/:path/
  elderyhelp:
    output: true
    permalink: /projects/eldery-help/:path/
  specialchild:
    output: true
    permalink: /projects/special-child/:path/
  tvstudio:
    output: true
    permalink: /projects/tvstudio/:path/
  sanddrawing:
    output: true
    permalink: /projects/sand-drawing/:path/
  ebru:
    output: true
    permalink: /projects/ebru/:path/
  longterm:
    output: true
    permalink: /projects/longterm/:path/
  children:
    output: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "adoptive-parents"
      type: pages
    values:
      section_breadcrumb: "/adoptive-parents/~Кандидатам в замещающие родители"
  -
    scope:
      path: "projects"
      type: pages
    values:
      section_breadcrumb: "/projects/~Проекты"
  -
    scope:
      path: "information"
      type: pages
    values:
      section_breadcrumb: "/information/~Сведения об образовательной организации"
  -
    scope:
      path: ""
      type: posts
    values:
      layout: "post"
      cover_image_key: 0
      files_subdir: life
      section_breadcrumb: "/life/~Новости"
  -
    scope:
      path: ""
      type: media
    values:
      layout: "post"
      cover_image_key: 0
      files_subdir: media
      section_breadcrumb: "/media/~СМИ о нас"
  -
    scope:
      path: ""
      type: announces
    values:
      layout: "post"
      cover_image_key: 0
      files_subdir: announces
      section_breadcrumb: "/announces/~Анонсы"
  -
    scope:
      path: "announces"
      type: pages
    values:
      section_breadcrumb: "/announces/~Анонсы"
  -
    scope:
      path: ""
      type: montessori
    values:
      layout: "post"
      cover_image_key: 0
      files_subdir: montessori
      section_breadcrumb: "/projects/~Проекты|/projects/montessori/~Монтессори-технологии в Центре"
  -
    scope:
      path: ""
      type: elderyhelp
    values:
      layout: "post"
      cover_image_key: 0
      files_subdir: eldery-help
      section_breadcrumb: "/projects/~Проекты|/projects/eldery-help/~Помощь пожилым людям"
  -
    scope:
      path: ""
      type: specialchild
    values:
      layout: "post"
      cover_image_key: 0
      files_subdir: special-child
      section_breadcrumb: "/projects/~Проекты|/projects/special-child/~Особый ребёнок. Всё обо всём"
  -
    scope:
      path: ""
      type: tvstudio
    values:
      layout: "post"
      single_image: true
      files_subdir: tvstudio
      section_breadcrumb: "/projects/~Проекты|/projects/tvstudio/~Наша телестудия"
  -
    scope:
      path: ""
      type: sanddrawing
    values:
      layout: "post"
      cover_image_key: 0
      files_subdir: sand-drawing
      section_breadcrumb: "/projects/~Проекты|/projects/sand-drawing/~Чудеса из песка (песочное рисование)"
  -
    scope:
      path: ""
      type: ebru
    values:
      layout: "post"
      cover_image_key: 0
      files_subdir: ebru
      section_breadcrumb: "/projects/~Проекты|/projects/ebru/~Рисование в технике Эбру"
  -
    scope:
      path: ""
      type: longterm
    values:
      layout: "post"
      cover_image_key: 0
      files_subdir: longterm
      section_breadcrumb: "/projects/~Проекты|/projects/longterm/~Долговременный уход"
  -
    scope:
      path: ""
      type: albums
    values:
      layout: "album"
      cover_image_key: 0
      section_breadcrumb: "/gallery/~Галерея"
  -
    scope:
      path: ""
      type: children
    values:
      single_image: true
      files_subdir: children
      no_more_link: true
